"""remove is_online

Historical note: still references table name ``connector_runtimes`` (pre-rename).
Current ORM model: ``connector_instances`` / ``ConnectorInstance``.

Revision ID: a7f8064a31c2
Revises: 8e689a84cae9
Create Date: 2026-03-29 04:05:22.986984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f8064a31c2'
down_revision: Union[str, Sequence[str], None] = '8e689a84cae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connector_runtimes', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector_runtimes', sa.Column('is_online', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
