"""add customers and customer_attributes

Revision ID: 1300a798a2bc
Revises: 74fc9d2c768e
Create Date: 2026-04-15 19:39:14.367793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1300a798a2bc'
down_revision: Union[str, Sequence[str], None] = '74fc9d2c768e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_role', sa.Enum('admin', 'member', 'viewer', name='customer_tenant_role'), nullable=True),
    sa.Column('plan_tier', sa.Enum('free', 'basic', 'pro', 'enterprise', name='customer_plan_tier'), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'key', name='uq_customer_attributes_customer_id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_attributes')
    op.drop_table('customers')
    # Drop PG enum types created in upgrade
    op.execute('DROP TYPE IF EXISTS customer_tenant_role')
    op.execute('DROP TYPE IF EXISTS customer_plan_tier')
    # ### end Alembic commands ###
