"""rework connectors

Historical note: introduces table ``connector_runtimes`` and column ``runtime_id``.
Later revisions rename these to ``connector_instances`` / ``instance_id`` to match
the domain model (see 2026_04_04_1200 and 2026_04_04_1400). Do not edit the DDL
identifiers here — they must stay as-is for existing databases.

Revision ID: 8e689a84cae9
Revises: dfca5b9e6818
Create Date: 2026-03-29 01:42:30.339564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e689a84cae9'
down_revision: Union[str, Sequence[str], None] = 'dfca5b9e6818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_runtimes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('runtime_id', sa.String(length=255), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_online', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_id', name='uq_connector_runtimes_runtime_id')
    )
    op.create_index(op.f('ix_connector_runtimes_runtime_id'), 'connector_runtimes', ['runtime_id'], unique=True)
    op.add_column('applications', sa.Column('required_connector_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.drop_column('applications', 'snapshot_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('snapshot_url', sa.VARCHAR(length=2048), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('applications', 'required_connector_tags')
    op.drop_index(op.f('ix_connector_runtimes_runtime_id'), table_name='connector_runtimes')
    op.drop_table('connector_runtimes')
    # ### end Alembic commands ###
