"""add employee provider mapping and record match

Revision ID: a039d6241e40
Revises: h8c9d0e1f2a3
Create Date: 2026-03-24 23:56:24.534836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a039d6241e40'
down_revision: Union[str, Sequence[str], None] = 'h8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_provider_attribute_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('employee_record_key', sa.String(length=255), nullable=False),
    sa.Column('employee_key', sa.String(length=255), nullable=False),
    sa.Column('is_determinator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_upstream', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'employee_record_key', name='uq_emp_prov_attr_map_app_id_record_key')
    )
    op.create_table('employee_record_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_record_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('matched_via_determinator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_record_id'], ['employee_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_record_id', name='uq_employee_record_matches_employee_record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_record_matches')
    op.drop_table('employee_provider_attribute_mappings')
    # ### end Alembic commands ###
