"""add resource and resource_attribute tables

Revision ID: d82f0a7485d4
Revises: 465335092e1e
Create Date: 2026-04-17 00:47:59.946753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82f0a7485d4'
down_revision: Union[str, Sequence[str], None] = '465335092e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('privilege_level', sa.Enum('admin', 'write', 'read', 'none', name='resource_privilege_level'), nullable=True),
    sa.Column('environment', sa.Enum('production', 'staging', 'dev', name='resource_environment'), nullable=True),
    sa.Column('data_sensitivity', sa.Enum('pii', 'financial', 'public', name='resource_data_sensitivity'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'external_id', name='uq_resources_application_id_external_id')
    )
    op.create_index('ix_resources_application_id', 'resources', ['application_id'], unique=False)
    op.create_index('ix_resources_kind', 'resources', ['kind'], unique=False)
    op.create_table('resource_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'key', name='uq_resource_attributes_resource_id_key')
    )
    op.drop_index(op.f('ix_applications_code'), table_name='applications')
    op.create_index(op.f('ix_applications_code'), 'applications', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_code'), table_name='applications')
    op.create_index(op.f('ix_applications_code'), 'applications', ['code'], unique=False)
    op.drop_table('resource_attributes')
    op.drop_index('ix_resources_kind', table_name='resources')
    op.drop_index('ix_resources_application_id', table_name='resources')
    op.drop_table('resources')
    op.execute('DROP TYPE IF EXISTS resource_privilege_level')
    op.execute('DROP TYPE IF EXISTS resource_environment')
    op.execute('DROP TYPE IF EXISTS resource_data_sensitivity')
    # ### end Alembic commands ###
