"""rework applications

Historical note: this revision added ``connector_id`` on ``applications``. That column
was never represented in the final ORM model; connector routing uses
``required_connector_tags`` (see revision ``8e689a84cae9``) and rows in
``connector_instances``. The legacy column is dropped in revision ``c1d2e3f4a5b6``.

Revision ID: dfca5b9e6818
Revises: a039d6241e40
Create Date: 2026-03-28 03:32:07.681404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfca5b9e6818'
down_revision: Union[str, Sequence[str], None] = 'a039d6241e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('connector_id', sa.String(length=255), server_default=sa.text('gen_random_uuid()::text'), nullable=False))
    op.add_column('applications', sa.Column('snapshot_url', sa.String(length=2048), server_default=sa.text("''"), nullable=False))
    op.create_index(op.f('ix_applications_connector_id'), 'applications', ['connector_id'], unique=True)
    op.create_unique_constraint(None, 'applications', ['name'])
    op.drop_column('applications', 'connector_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('connector_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_index(op.f('ix_applications_connector_id'), table_name='applications')
    op.drop_column('applications', 'snapshot_url')
    op.drop_column('applications', 'connector_id')
    # ### end Alembic commands ###
