"""add access_artifacts table

Revision ID: f8369314b4e5
Revises: d82f0a7485d4
Create Date: 2026-04-17 01:50:47.822196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8369314b4e5'
down_revision: Union[str, Sequence[str], None] = 'd82f0a7485d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_artifacts_application_id', 'access_artifacts', ['application_id'], unique=False)
    op.create_index('ix_access_artifacts_ingested_at', 'access_artifacts', [sa.literal_column('ingested_at DESC')], unique=False)
    op.create_index('ix_access_artifacts_source_kind', 'access_artifacts', ['source_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_artifacts_source_kind', table_name='access_artifacts')
    op.drop_index('ix_access_artifacts_ingested_at', table_name='access_artifacts')
    op.drop_index('ix_access_artifacts_application_id', table_name='access_artifacts')
    op.drop_table('access_artifacts')
    # ### end Alembic commands ###
