"""add buffer logging

Revision ID: 74fc9d2c768e
Revises: b8c9d0e1f2a3
Create Date: 2026-04-05 22:58:09.844976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fc9d2c768e'
down_revision: Union[str, Sequence[str], None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_name_key'), 'applications', type_='unique')
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=True)
    op.create_unique_constraint('uq_applications_name', 'applications', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_applications_name', 'applications', type_='unique')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.create_unique_constraint(op.f('applications_name_key'), 'applications', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
